(ns automotive.render-html
  "Build-time HTML renderer for `docs/samples/operator-console.html`.

  Closes flagship checklist item 2 (ADR-2607189300 at
  `com-junkawasaki/root`, ledger seq 3 diagnosis / seq 4 fix): this page
  was previously a ONE-TIME hand-pasted transcript of a
  `clojure -M:dev:run` console session -- despite its own caption
  claiming 'Demo snapshot -- live data from `automotive.store` /
  `clojure -M:dev:run`', the file was never actually regenerated by
  running that command again (git history: exactly one commit ever
  touched it, alongside the whole `docs/` tree, no companion script).

  This namespace makes that caption true: it runs the SAME
  motor-vehicle demo scenario `automotive.sim`/`automotive.export-run`
  already exercise, through the REAL actor stack
  (`automotive.operation` -> `automotive.governor` ->
  `automotive.store`), and renders the result deterministically.
  No invented numbers, no timestamps in the page content -- reruns
  against the same fresh seed produce byte-identical output (verified
  by diffing two consecutive runs), so nightly regeneration only ever
  commits when the actor's real behavior actually changes, the same
  'commit-only-on-change' discipline `cloud-itonami-isic-6399`'s
  `web/generate.cljs` + `regenerate.yml` established for this fleet.

  Usage: `clojure -M:dev:render-html [out-file]`
  (default `docs/samples/operator-console.html`)."
  (:require [clojure.string :as str]
            [automotive.store :as store]
            [automotive.export :as export]
            [automotive.operation :as op]
            [langgraph.graph :as g]))

(def ^:private operator
  {:actor-id "op-1" :actor-role :homologation-engineer :phase 3})

(defn- exec! [actor tid request]
  (g/run* actor {:request request :context operator} {:thread-id tid}))

(defn- approve! [actor tid]
  (g/run* actor {:approval {:status :approved :by "op-1"}}
          {:thread-id tid :resume? true}))

(defn run-demo!
  "Runs a fresh seeded store through the same interesting-state
  scenario this page has always described: vehicle-1 clears the full
  lifecycle (intake -> type-approval verify -> end-of-line screen ->
  robotics/CAE assembly-line check -> vehicle-dispatch -> Certificate
  of Conformity, each human-gated step actually approved); vehicle-2
  HARD-holds on a missing type-approval spec basis (never reaches a
  human); vehicle-3 clears verification and its own robotics/CAE
  check but HARD-holds at dispatch on an out-of-range emissions
  deviation; vehicle-4 HARD-holds on an unresolved end-of-line defect
  (never reaches a human). Returns the resulting store -- every field
  read by `render` below is real governor/store output, not a
  hand-typed copy."
  []
  (let [db (store/seed-db)
        actor (op/build db)]
    (exec! actor "v1-intake" {:op :vehicle/intake :subject "vehicle-1"
                               :patch {:id "vehicle-1" :vehicle-name "Sakura Compact Sedan CS-04"}})
    (exec! actor "v1-verify" {:op :type-approval-rules/verify :subject "vehicle-1"})
    (approve! actor "v1-verify")
    (exec! actor "v1-eol" {:op :end-of-line-quality/screen :subject "vehicle-1"})
    (approve! actor "v1-eol")
    (exec! actor "v1-robotics" {:op :robotics/simulate-assembly-line :subject "vehicle-1"})
    (approve! actor "v1-robotics")
    (exec! actor "v1-dispatch" {:op :actuation/dispatch-vehicle :subject "vehicle-1"})
    (approve! actor "v1-dispatch")
    (exec! actor "v1-cert" {:op :actuation/issue-conformity-certificate :subject "vehicle-1"})
    (approve! actor "v1-cert")

    (exec! actor "v2-verify" {:op :type-approval-rules/verify :subject "vehicle-2" :no-spec? true})

    (exec! actor "v3-verify" {:op :type-approval-rules/verify :subject "vehicle-3"})
    (approve! actor "v3-verify")
    (exec! actor "v3-robotics" {:op :robotics/simulate-assembly-line :subject "vehicle-3"})
    (approve! actor "v3-robotics")
    (exec! actor "v3-dispatch" {:op :actuation/dispatch-vehicle :subject "vehicle-3"})

    (exec! actor "v4-eol" {:op :end-of-line-quality/screen :subject "vehicle-4"})
    db))

;; ----------------------------- rendering -----------------------------

(defn- esc [v]
  (-> (str v)
      (str/replace "&" "&amp;")
      (str/replace "<" "&lt;")
      (str/replace ">" "&gt;")))

(defn- last-fact-for [ledger vehicle-id]
  (last (filter #(= (:subject %) vehicle-id) ledger)))

(defn- emissions-cell [{:keys [emissions-deviation-actual emissions-deviation-min emissions-deviation-max]}]
  (if (and (number? emissions-deviation-actual)
           (<= emissions-deviation-min emissions-deviation-actual emissions-deviation-max))
    (format "<span class=\"ok\">%.2f &isin; [%.2f,%.2f]</span>"
            (double emissions-deviation-actual) (double emissions-deviation-min) (double emissions-deviation-max))
    (format "<span class=\"err\">%.2f out of range</span>" (double emissions-deviation-actual))))

(defn- eol-cell [{:keys [eol-defect-unresolved?]}]
  (if eol-defect-unresolved?
    "<span class=\"err\">unresolved</span>"
    "<span class=\"ok\">resolved</span>"))

(defn- status-cell [ledger {:keys [id vehicle-dispatched? conformity-certified?]}]
  (let [last-fact (last-fact-for ledger id)]
    (cond
      (and vehicle-dispatched? conformity-certified?)
      "<span class=\"ok\">ready</span>"

      (= :hold (:disposition last-fact))
      (let [rule (-> last-fact :violations first :rule)]
        (case rule
          :no-spec-basis "<span class=\"err\">no spec-basis</span>"
          :end-of-line-defect-unresolved "<span class=\"critical\">EOL hold</span>"
          :vehicle-emissions-out-of-range "<span class=\"warn\">HARD hold on dispatch</span>"
          (str "<span class=\"warn\">HARD hold: " (esc (name (or rule :unknown))) "</span>")))

      :else "<span class=\"muted\">in progress</span>")))

(defn- vehicle-row [ledger {:keys [id vehicle-name jurisdiction] :as vehicle}]
  (format "        <tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>"
          (esc id) (esc vehicle-name) (esc jurisdiction)
          (emissions-cell vehicle) (eol-cell vehicle) (status-cell ledger vehicle)))

(defn- record-row [record kind note]
  (format "        <tr><td>%s</td><td>%s</td><td>%s</td></tr>"
          (esc (get record "record_id")) (esc kind) (esc note)))

(def ^:private action-gate-rows
  ;; Static description of this actor's own op contract (README `Ops`
  ;; table, `automotive.governor`/`automotive.phase`) -- documentation
  ;; of fixed behavior, not runtime telemetry, so it is legitimately
  ;; hand-described rather than derived from a live run.
  ["        <tr><td><code>:vehicle/intake</code></td><td>none</td><td><span class=\"ok\">phase-3 auto when clean</span></td></tr>"
   "        <tr><td><code>:type-approval-rules/verify</code></td><td>none</td><td><span class=\"warn\">human approval &middot; no fabricated type-approval rules</span></td></tr>"
   "        <tr><td><code>:end-of-line-quality/screen</code></td><td>none</td><td><span class=\"critical\">HARD hold if unresolved defect</span></td></tr>"
   "        <tr><td><code>:robotics/simulate-assembly-line</code></td><td>none</td><td><span class=\"warn\">human approval &middot; real physics-2d CAE check</span></td></tr>"
   "        <tr><td><code>:actuation/dispatch-vehicle</code></td><td class=\"critical\">safety-critical</td><td><span class=\"warn\">always human &middot; emissions + robotics-sim checks</span></td></tr>"
   "        <tr><td><code>:actuation/issue-conformity-certificate</code></td><td class=\"critical\">safety-critical</td><td><span class=\"warn\">always human &middot; EOL + double-issue guard</span></td></tr>"])

(defn render
  "Renders the full operator-console.html document from a store `db`
  that has already run `run-demo!` (or any other real scenario)."
  [db]
  (let [ledger (vec (store/ledger db))
        vehicles (->> (export/vehicles-snapshot db)
                      (filter #(#{"vehicle-1" "vehicle-2" "vehicle-3" "vehicle-4"} (:id %)))
                      (sort-by :id))
        dispatches (store/dispatch-history db)
        certs (store/evidence-history db)
        vehicle-rows (str/join "\n" (map (partial vehicle-row ledger) vehicles))
        dispatch-rows (str/join "\n" (map #(record-row % "vehicle-dispatch-draft" "unsigned · plant signs offline") dispatches))
        cert-rows (str/join "\n" (map #(record-row % "conformity-certificate-draft" "unsigned · type-approval authority submission is plant act") certs))
        handoff-rows (str/join "\n" (remove str/blank? [dispatch-rows cert-rows]))]
    (str
     "<html><head><meta charset=\"utf-8\"><title>cloud-itonami-isic-2910 · motor-vehicle plant</title><style>\n"
     "table { width: 100%; border-collapse: collapse; font-size: 14px; }\n"
     ".ok { color: #137a3f; }\n"
     "body { font-family: system-ui,-apple-system,sans-serif; margin: 0; color: #1a1a1a; background: #fafafa; }\n"
     "header.bar { display: flex; align-items: center; gap: 12px; padding: 12px 20px; background: #fff; border-bottom: 1px solid #e5e5e5; }\n"
     "th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #f0f0f0; }\n"
     "h2 { margin-top: 0; font-size: 15px; }\n"
     ".warn { color: #b25c00; background: #fff8e1; padding: 2px 6px; border-radius: 4px; }\n"
     "main { max-width: 980px; margin: 24px auto; padding: 0 20px; }\n"
     "header.bar h1 { font-size: 18px; margin: 0; font-weight: 600; }\n"
     ".muted { color: #888; font-size: 13px; }\n"
     ".critical { color: #fff; background: #b3261e; padding: 2px 6px; border-radius: 4px; font-weight: 600; }\n"
     ".card { background: #fff; border: 1px solid #e5e5e5; border-radius: 8px; padding: 16px; margin-bottom: 16px; }\n"
     ".err { color: #b3261e; background: #fbe9e7; padding: 2px 6px; border-radius: 4px; }\n"
     "th { font-weight: 600; color: #555; font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; }\n"
     "header.bar .badge { margin-left: auto; font-size: 12px; color: #666; }\n"
     "code { font-size: 12px; background: #f4f4f4; padding: 1px 4px; border-radius: 3px; }\n"
     "</style></head><body>\n"
     "<header class=\"bar\">\n"
     "  <h1>Motor-vehicle plant (ISIC 2910) — Operator Console</h1>\n"
     "  <span class=\"badge\">read-only sample · governor-gated · never dispatches hardware</span>\n"
     "</header>\n"
     "<main>\n"
     "  <section class=\"card\">\n"
     "    <h2>Vehicles</h2>\n"
     "    <p class=\"muted\">Demo snapshot — build-time-generated from <code>automotive.store</code> via <code>automotive.render-html</code> (<code>clojure -M:dev:render-html</code>), regenerated nightly.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Vehicle</th><th>Name</th><th>Jurisdiction</th><th>Emissions</th><th>EOL</th><th>Status</th></tr></thead>\n"
     "      <tbody>\n"
     vehicle-rows "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"
     "  <section class=\"card\">\n"
     "    <h2>Action gate (Automotive Governor)</h2>\n"
     "    <p class=\"muted\">HARD holds cannot be overridden. Actuation always escalates to a human homologation engineer.</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Op</th><th>Stake</th><th>Gate</th></tr></thead>\n"
     "      <tbody>\n"
     (str/join "\n" action-gate-rows) "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"
     "  <section class=\"card\">\n"
     "    <h2>Social hand-off</h2>\n"
     "    <p class=\"muted\">Audit package for type-approval inspectors / market-regulator inspectors — <code>automotive.export/audit-package</code> and <code>package-&gt;csv-bundle</code> (vehicles / ledger / dispatches / conformity-certificates CSV).</p>\n"
     "    <table>\n"
     "      <thead><tr><th>Artifact</th><th>Kind</th><th>Note</th></tr></thead>\n"
     "      <tbody>\n"
     handoff-rows "\n"
     "      </tbody>\n"
     "    </table>\n"
     "  </section>\n"
     "</main>\n"
     "</body></html>\n")))

(defn -main [& args]
  (let [out (or (first args) "docs/samples/operator-console.html")
        db (run-demo!)
        html (render db)]
    (spit out html)
    (println "wrote" out "(" (count (store/ledger db)) "ledger facts,"
             (count (store/dispatch-history db)) "dispatches,"
             (count (store/evidence-history db)) "conformity certificates )")))
